x-app-environment: &app-environment
  APP_ENV: dev
  APP_DEBUG: 1
  APP_SECRET: 75914121030ad559bbae482519258ce1
  DATABASE_URL: "postgresql://my_postgres:postgres@cs-pg-integration:5432/integration_broker_db?serverVersion=17&charset=utf8"
  REDIS_URL: "redis://cs-redis:6379"
  MESSENGER_TRANSPORT_DSN: "amqp://my_rabbit:rabbit@cs-rabbitmq:5672/integration"
  RABBITMQ_HOST: "cs-rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "my_rabbit"
  RABBITMQ_PASS: "rabbit"
  RABBITMQ_VHOST: "integration"
  BROKER_API_BASE_URL: "http://wiremock:8080"
  OUTBOX_DELAY_MS: "30000"
  MONOLOG_SOCKET_HOST: "tcp://buggregator:9913"

services:
  integration-broker-api:
    image: integration-broker-api-image
    container_name: integration-broker-api
    build:
      context: .
      dockerfile: ./Docker/RR/Dockerfile
    volumes:
      - ./app:/var/www/html
    environment:
      <<: *app-environment
      APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime
      VAR_DUMPER_FORMAT: server
      VAR_DUMPER_SERVER: buggregator:9912
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=integration_demo_net"
      - "traefik.http.services.integration-broker-api.loadbalancer.server.port=8080"
      - "traefik.http.routers.integration-broker-api.rule=Host(`api.integration-demo.local`) && (Path(`/health`) || PathPrefix(`/api/v1/investments/`))"
      - "traefik.http.routers.integration-broker-api.entrypoints=web"
      - "traefik.http.routers.integration-broker-api.service=integration-broker-api"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - integration_demo_net

  integration-broker-api-php-cli:
    image: integration-broker-api-php-cli-image
    container_name: integration-broker-api-php-cli
    build:
      context: .
      dockerfile: ./Docker/cli/Dockerfile
    volumes:
      - ./app:/var/www/html
    environment:
      <<: *app-environment
    networks:
      - integration_demo_net

  integration-broker-api-outbox-relay:
    image: integration-broker-api-php-cli-image
    container_name: integration-broker-api-outbox-relay
    build:
      context: .
      dockerfile: ./Docker/cli/Dockerfile
    command:
      [
        "sh",
        "-c",
        "php bin/console cache:clear --no-warmup && exec php bin/console messenger:consume outbox --no-interaction -vv --sleep=1",
      ]
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
    environment:
      <<: *app-environment
    networks:
      - integration_demo_net

networks:
  integration_demo_net:
    external: true
